# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]

-   repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
    -   id: gradle-check
        args: ['-w', --wrapper]
        stages: [push]
